### ISSUE TITLE
Script not working for non Arch packages [possibly feature request]

### ISSUE THREAD

**Issue by dr460nf1r3** [ivan-hc/Arch-Deployer#4]
Hey :) so basically I tried packaging a package which is not present in the official Arch repos, which failed though. The package itself is present in a user repository ([Chaotic-AUR](https://aur.chaotic.cx)) though and installed at my own system. 
[Logs](https://bin.garudalinux.org/?88a2428db33d82b1#BZ6A38LDXGuJqV8xU4p1HYgjVLrHvJ8KrCdxndcbBuct) in case it helps. 

It seems like custom repositories are not supported at this point if I'm not mistaken, so this is probably a feature request. Ultimately my goal is to package the [FireDragon browser](https://aur.archlinux.org/packages/firedragon/) using this tool :)

**Comment by ivan-hc** [comment]
Hi, and Happy New Year! :)
I'm trying to add a line for Chaotic AUR, the script should look like this:

      `#!/bin/sh
       
       for APP in $1; do
	   mkdir -p ./$1
	   cd ./$1
	   ARCH=$(uname -m)
	   MIRROR="https://archlinux.org/packages/"
	   CHAOTICAUR="https://cdn-mirror.chaotic.cx/chaotic-aur/"
	   for REPO in { "core" "extra" "community" "multilib" }; do
	   wget ${MIRROR}/${REPO}/${ARCH}/$APP/download && mv ./download ./$APP.tar.zst
	LINE 11 --->  ?????????????????? <---
	   done
           .....`

as you can see, the only problem is to find a command that can check the correct package (at line 11), but on the list I have `firedragon` and `firedragon-ng` that can conflict each other.

The only solution for now would be to use  `wget` the way that Arch-Deployer can download directly `firedragon-95.0.2-2-x86_64.pkg.tar.zst`, i.e.

      `./arch-deployer firedragon-95.0.2-2-x86_64.pkg.tar.zst`

This is the easier solution, the command would be look like this:

`wget ${CHAOTICAUR}/${ARCH}/firedragon-95.0.2-2-x86_64.pkg.tar.zst && break`

Another solution would be to add this line instead:

`wget -r -A $APP*.tar.zst -nd ${GARUDA}/${ARCH}/ && break`

where `$APP` must be `firedragon-95` and `${GARUDA}` is `GARUDA=https://builds.garudalinux.org/repos/chaotic-aur/` must be at line 8 (instead of `CHAOTICAUR="https://cdn-mirror.chaotic.cx/chaotic-aur/"`).

These are not the best solutions, but they are the only two I've tested that are working for me.

SPOILER: when the AppDir is opened, there are some things to modify (for example "Exec=" in the .desktop file, and other "moz"-related missing libraries that are not found from the AppImage, when I launch it (maybe from `kfiredragonhelper`, that are not downloaded during my tests, I should add the same modifications at line 23-24).

Let me know if you have more success.

**Comment by ivan-hc** [comment]
Here is how the script should look like with the newer modifications:

      `#!/bin/sh

      for APP in $1; do
		mkdir -p ./$1
		cd ./$1
		ARCH=$(uname -m)
		MIRROR="https://archlinux.org/packages/"
		CHAOTICAUR="https://builds.garudalinux.org/repos/chaotic-aur/"
		for REPO in { "core" "extra" "community" "multilib" }; do
		wget ${MIRROR}/${REPO}/${ARCH}/$APP/download && mv ./download ./$APP.tar.zst
		wget -r -A $APP*.tar.zst -nd ${CHAOTICAUR}/${ARCH}/ && break
		done
		tar fx ./*.tar.zst
		DEP=$( cat ./.PKGINFO | grep "depend" | grep -v "makedepend" | grep -v "optdepend" | cut -c 10- )
		echo $DEP | tr ' ' '\n' >> DEP
		MAKEDEP=$( cat ./.PKGINFO | grep "makedepend" | cut -c 14- )
		echo $MAKEDEP | tr ' ' '\n' >> DEP
		awk '{ print "\""$0"\""}' DEP
		ARGS=$( cat ./DEP )
		for VAR in ${ARGS} ; do
			for REPO in { "core" "extra" "community" "multilib" }; do
			wget ${MIRROR}/${REPO}/${ARCH}/$VAR/download && mv ./download ./$VAR.tar.zst
			wget -r -A $VAR*.tar.zst -nd ${CHAOTICAUR}/${ARCH}/ && break 
			done
			ARGS=$( cat ./DEP )
		done
		for f in *.tar.zst; do 
			tar xf "$f"; 
		done
   
        ......etcetera...etcetera...etcetera...`

but this will download too many packages from Chaotic with the same keyword in the name. The keywords listed in "DEP" are:

`gtk3
libxt
mime-types
dbus-glib
ffmpeg
nss
ttf-font
libpulse
aom
harfbuzz
libvpx
libjpeg
zlib
icu
libevent
pipewire
kfiredragonhelper
unzip
zip
diffutils
yasm
mesa
imake
inetutils
ccache
rust
xorg-server-xwayland
xorg-server-xvfb
python-pip
autoconf2.13
clang
llvm
jack
nodejs
cbindgen
nasm
python-setuptools
python-psutil
python-zstandard
git
binutils
lld
dump_syms
wasi-compiler-rt
wasi-libc
wasi-libc++
wasi-libc++abi`

That's why I've prefered to use only the main repositories.

However it is possible to download other dependencies from Chaotic manually, if you prefer.

**Comment by ivan-hc** [comment]
PS: if you succeed, would you be interested in adding the package (AppImage or standalone tarball) to "AM"? 

SITE: https://github.com/ivan-hc/AM-application-manager

**Comment by ivan-hc** [comment]
Hey, I was able to start Firedragon as a standalone app (not an AppImage) on Debian Testing/Unstable, this way:

1. once downloaded/extracted the archive, replace the existing `/usr/lib/firedragon/libxul.so` with the one from Firefox;
2. run `/usr/lib/firedragon/firedragon`

Why don't you distribute your browser as a standalone bundle? That would be great!
Also creating an AppImage only with the content of `/usr/lib/firedragon` + AppRun + *.desktop file + *.svg/*.png would give you a lightweight AppImage (I've not bundled it as an AppImage, but [this guide](https://github.com/ivan-hc/appimage-sample) would be helpful for you).

**Comment by ivan-hc** [comment]
EDIT: I've finally created the AppImage! Here you are the "recipe".

RECIPE:

1. create the AppDir, download/extract the archive from chaotic-AUR, then replace the existing `/usr/lib/firedragon/libxul.so` with the one from Firefox;
2. copy/paste the .desktop file and the related icon in the main AppDir;
3. AppRun (from  [my guide](https://github.com/ivan-hc/appimage-sample), just replace the path of the line 11 with  `/usr/lib/firedragon/firedragon`), copy/paste it and made it executable:

       #!/bin/sh
       HERE="$(dirname "$(readlink -f "${0}")")"
       export PATH="${HERE}/usr/bin/:${HERE}/usr/sbin/:${HERE}/usr/games/:${HERE}/bin/:${HERE}/sbin/${PATH:+:$PATH}"
       export LD_LIBRARY_PATH="${HERE}/usr/lib/:${HERE}/usr/lib/i386-linux-gnu/:${HERE}/usr/lib/x86_64-linux-gnu/:${HERE}/usr/lib32/:${HERE}/usr/lib64/:${HERE}/lib/:${HERE}/lib/i386-linux-gnu/:${HERE}/lib/x86_64-linux-gnu/:${HERE}/lib32/:${HERE}/lib64/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
       export PYTHONPATH="${HERE}/usr/share/pyshared/${PYTHONPATH:+:$PYTHONPATH}"
       export XDG_DATA_DIRS="${HERE}/usr/share/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
       export PERLLIB="${HERE}/usr/share/perl5/:${HERE}/usr/lib/perl5/${PERLLIB:+:$PERLLIB}"
       export GSETTINGS_SCHEMA_DIR="${HERE}/usr/share/glib-2.0/schemas/${GSETTINGS_SCHEMA_DIR:+:$GSETTINGS_SCHEMA_DIR}"
       export QT_PLUGIN_PATH="${HERE}/usr/lib/qt4/plugins/:${HERE}/usr/lib/i386-linux-gnu/qt4/plugins/:${HERE}/usr/lib/x86_64-linux-gnu/qt4/plugins/:${HERE}/usr/lib32/qt4/plugins/:${HERE}/usr/lib64/qt4/plugins/:${HERE}/usr/lib/qt5/plugins/:${HERE}/usr/lib/i386-linux-gnu/qt5/plugins/:${HERE}/usr/lib/x86_64-linux-gnu/qt5/plugins/:${HERE}/usr/lib32/qt5/plugins/:${HERE}/usr/lib64/qt5/plugins/${QT_PLUGIN_PATH:+:$QT_PLUGIN_PATH}"
       EXEC="${HERE}/usr/lib/firedragon/firedragon"
       exec "${EXEC}"

4. Export everything to an AppImage, it works really well for me.

**Comment by dr460nf1r3** [comment]
Wow! I did not expect such a detailed and in-depth response, thanks for figuring this out for me :) 
I'll give it a shot and will report back. Once things work, I'm of course interested in adding the browser to your application manager!

**Comment by ivan-hc** [comment]
> Wow! I did not expect such a detailed and in-depth response, thanks for figuring this out for me :)
I'll give it a shot and will report back. Once things work, I'm of course interested in adding the browser to your application manager!

Sorry if i bother you, but i took the liberty of writing [an AM script for the FireDragon Web Browser](https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/x86_64/firedragon). As for all the applications managed by "AM", this script will create an /opt/firedragon folder containing all the program's files, an "AM-updater" and a "remove" script too, plus a link in /usr/local/bin/firedragon and a launcher in /usr/share/applications/firedragon.desktop. Updating it doesn't requires "root", but installing/removing it yes.

#### INSTALLATION (with "AM")

    sudo am -i firedragon
#### INSTALLATION (without "AM")

    wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/programs/x86_64/firedragon && chmod a+x ./firedragon && sudo ./firedragon
#### UPDATING (without "AM")

    /opt/firedragon/AM-updater
#### UPDATING (with "AM", this will update all the programs installed with "AM")

    am -u
#### REMOVING (without "AM")

    sudo /opt/firedragon/remove
#### REMOVING (with "AM")

    sudo am -r firedragon

NOTE, as I've already said previously

> Hey, I was able to start Firedragon as a standalone app (not an AppImage) on Debian Testing/Unstable, this way:
> 
>     1. once downloaded/extracted the archive, replace the existing `/usr/lib/firedragon/libxul.so` with the one from Firefox

So this script will download the latest version of Firefox too to get  the libxul.so file that allow Firedragon to work anywere (not just Arch Linux).

I hope you like it, you're free to modify this script if you prefer. Many of my scripts on AM Application Manager are edited the same way, and it is possible to get a template for each script with the command `am -t $APPNAME`. You can take a look to all the other script (for x86_64) at https://github.com/ivan-hc/AM-application-manager/tree/main/programs/x86_64

The keywords for the command `am -q $ARGUMENT` are:

     ◆ firedragon : Web Browser (Firefox/LibreWolf fork) with saner defaults.
You can read the information available with the command `am -a firedragon` at https://github.com/ivan-hc/AM-application-manager/blob/main/programs/.about/firedragon

**Comment by dr460nf1r3** [comment]
That's amazing! 🤩 I briefly checked it out, although there was something wrong with the URL the script was trying to download the FireDragon tar. Sadly didn't have the time to have a closer look but I really hope I do by the weekend!

**Comment by ivan-hc** [comment]
Hi, Arch Deployer 1.0 has been released five days ago.
Now to enable the "CHAOTICAUR" support, just uncomment the line 5 of the main script, here https://github.com/ivan-hc/Arch-Deployer/blob/bd8a8a985186687dbf5d3cb5601c6285d7fbf18f/arch-deployer#L5
If you install it using "AM" you can do this without root privileges (just edit the `/opt/arch-deployer/arch-deployer` script). I still have to solve the issue for the `exact-name-$(a-random-number)*.tar.zst`, where after any keyword you use (in `$1`, ie "xact-name"), the `$(a-random-number)` variable is the first part that follows the request.
Any suggestion?
