### ISSUE TITLE
Deployed Package can't access the user's directory. 

### ISSUE THREAD

**Issue by GuangDai** [ivan-hc/Arch-Deployer#5]
Thanks for your awesome deployer script. I use it to deploy qbittorrent-enhanced-qt5. I find that the appimage can't access to the outside dir. Any idea how to fix it? I don't know much about the rule of appimage, but I may help you at my best.

![image](https://user-images.githubusercontent.com/59678726/170160854-20a8ae27-ae38-4359-93e4-5c202aea730e.png)

**Comment by ivan-hc** [comment]
Hi, to solve this issue, you should add `/:` to `UNION_PRELOAD` in the AppRun, ie this line:

    export UNION_PRELOAD="${HERE}"
must be like this:

    export UNION_PRELOAD=/:"${HERE}"

If you're interested in qbittorrent, this is the AppRun I've used to create a "lite version" from a PPA:

    #!/bin/sh
    SELF=$(readlink -f "$0")
    HERE=${SELF%/*}
    export PATH="${HERE}/usr/bin/:${HERE}/usr/lib/mime/packages/:${HERE}/usr/lib/x86_64-linux-gnu/:${HERE}/usr/share/doc/libtorrent-rasterbar10/:${HERE}/usr/share/doc/qbittorrent/:${HERE}/usr/man/man1/:${HERE}/usr/share/metainfo/${PATH:+:$PATH}"
    export LD_LIBRARY_PATH="${HERE}/usr/lib/:${HERE}/usr/lib/x86_64-linux-gnu/:${HERE}/usr/lib/mime/:${HERE}/usr/share/doc/libtorrent-rasterbar10/:${HERE}/usr/share/doc/qbittorrent/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
    export XDG_DATA_DIRS="${HERE}/usr/share/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
    EXEC="${HERE}/usr/bin/qbittorrent"
    EXEC=$(grep -e ^Exec=.* "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)
    exec "${EXEC}" "$@"

From the istallation script for "AM", at https://github.com/ivan-hc/AM-Application-Manager/blob/main/programs/x86_64/qbittorrent-lite

this instead is the AppRun I use for the AppImage of KDEutils (including "filelight", a Baobab-like utility for KDE that needs to read the root file system too):

    #!/bin/sh
    HERE="$(dirname "$(readlink -f "${0}")")"
    export UNION_PRELOAD=/:"${HERE}"
    export LD_PRELOAD="${HERE}/libunionpreload.so"
    export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:"${HERE}"/usr/bin/:"${HERE}"/usr/sbin/:"${HERE}"/usr/games/:"${HERE}"/bin/:"${HERE}"/opt/kdeutils/:"${HERE}"/sbin/:"${PATH}"
    export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${LD_LIBRARY_PATH}"
    export PYTHONPATH="${HERE}"/usr/share/pyshared/:"${PYTHONPATH}"
    export PYTHONHOME="${HERE}"/usr/
    export XDG_DATA_DIRS="${HERE}"/usr/share/:"${XDG_DATA_DIRS}"
    export PERLLIB="${HERE}"/usr/share/perl5/:"${HERE}"/usr/lib/perl5/:"${PERLLIB}"
    export GSETTINGS_SCHEMA_DIR="${HERE}"/usr/share/glib-2.0/schemas/:"${GSETTINGS_SCHEMA_DIR}"
    export QT_PLUGIN_PATH="${HERE}"/usr/lib/qt4/plugins/:"${HERE}"/usr/lib/i386-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt4/plugins/:"${HERE}"/usr/lib32/qt4/plugins/:"${HERE}"/usr/lib64/qt4/plugins/:"${HERE}"/usr/lib/qt5/plugins/:"${HERE}"/usr/lib/i386-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib/x86_64-linux-gnu/qt5/plugins/:"${HERE}"/usr/lib32/qt5/plugins/:"${HERE}"/usr/lib64/qt5/plugins/:"${QT_PLUGIN_PATH}"
    case $1 in
    ark|filelight|kcalc|kcharselect|kdf|kgpg|ktimer|kwalletmanager5|sweeper) if test -f "${HERE}"/usr/bin/$1; then
    cd "${HERE}"/usr/share/kxmlgui5
    EXEC=$(grep -e '^Exec=.*' "${HERE}"/usr/share/applications/org.kde.$1.desktop | head -n 1 | cut -d "=" -f 2- | sed -e 's|%.||g')
    exec ${EXEC} "$@" 2>/dev/null
    exit
    esac

from https://github.com/ivan-hc/AM-Application-Manager/blob/main/programs/x86_64/kdeutils

just to take you an idea on how the AppRun works.

I hope this helps you

**Comment by GuangDai** [comment]
Thanks for your great and detailed answer. It really helps me. Thanks!
